In [12]:
import pandas as pd
from scipy.stats import pearsonr
import matplotlib.pyplot as plt
import seaborn as sns

In [13]:
age_df = pd.read_csv('data/age.csv')
data_df = pd.read_csv('data/data.csv')

print("Age Data Info:")
print(age_df.info())
print(age_df.head())

print("\nData Data Info:")
print(data_df.info())
print(data_df.head())

Age Data Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Пацієнт  200 non-null    int64
 1   Вік      200 non-null    int64
 2   Стать    200 non-null    int64
dtypes: int64(3)
memory usage: 4.8 KB
None
   Пацієнт  Вік  Стать
0        1   35      1
1        2   23      2
2        3   41      2
3        4   42      2
4        5   25      2

Data Data Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Columns: 174 entries, Пацієнт to Cup Area mm2
dtypes: float64(141), int64(32), object(1)
memory usage: 543.9+ KB
None
   Пацієнт  Обстеження Око  Гострота зору некорегована далека відстань  \
0        1           1   d                                         NaN
1        1           1   s                                        0.05
2        2           1   d                                        0.04
3        2           1   s                                        0.04
4        3           1   d                                        0.20

   Корекція sph  Корекція cyl  Корекція cyl ax  \
0         -4.00          0.00              0.0
1         -3.75         -0.50             10.0
2         -3.00         -1.00            100.0
3         -3.00         -0.75             15.0
4         -1.00          0.00              0.0

   Гострота зору максимально корегована далека відстань  \
0                                                1.0
1                                                1.0
2                                                0.8
3                                                0.8
4                                                0.9

   Гострота зору некорегована далека відстань циклоплегія  \
0                                               0.05
1                                               0.05
2                                               0.04
3                                               0.04
4                                               0.20

   Корекція циклоплегія sph  ...  TSNIT S  TSNIT N  TSNIT I  TSNIT T  \
0                     -3.50  ...      NaN      NaN      NaN      NaN
1                     -3.50  ...      NaN      NaN      NaN      NaN
2                     -2.75  ...      NaN      NaN      NaN      NaN
3                     -2.75  ...      NaN      NaN      NaN      NaN
4                     -0.50  ...      NaN      NaN      NaN      NaN

   C/D Horizon  C/D Vertical  R/D (Min)  R/D Angle  DiscArea mm2  Cup Area mm2
0          NaN           NaN        NaN        NaN           NaN           NaN
1          NaN           NaN        NaN        NaN           NaN           NaN
2          NaN           NaN        NaN        NaN           NaN           NaN
3          NaN           NaN        NaN        NaN           NaN           NaN
4          NaN           NaN        NaN        NaN           NaN           NaN

[5 rows x 174 columns]

In [14]:
merged_df = pd.merge(data_df, age_df, on='Пацієнт', how='left')
print(merged_df.head())
print(merged_df.info())
merged_df.to_csv('data/merged_data.csv', index=False)

   Пацієнт  Обстеження Око  Гострота зору некорегована далека відстань  \
0        1           1   d                                         NaN
1        1           1   s                                        0.05
2        2           1   d                                        0.04
3        2           1   s                                        0.04
4        3           1   d                                        0.20

   Корекція sph  Корекція cyl  Корекція cyl ax  \
0         -4.00          0.00              0.0
1         -3.75         -0.50             10.0
2         -3.00         -1.00            100.0
3         -3.00         -0.75             15.0
4         -1.00          0.00              0.0

   Гострота зору максимально корегована далека відстань  \
0                                                1.0
1                                                1.0
2                                                0.8
3                                                0.8
4                                                0.9

   Гострота зору некорегована далека відстань циклоплегія  \
0                                               0.05
1                                               0.05
2                                               0.04
3                                               0.04
4                                               0.20

   Корекція циклоплегія sph  ...  TSNIT I  TSNIT T  C/D Horizon  C/D Vertical  \
0                     -3.50  ...      NaN      NaN          NaN           NaN
1                     -3.50  ...      NaN      NaN          NaN           NaN
2                     -2.75  ...      NaN      NaN          NaN           NaN
3                     -2.75  ...      NaN      NaN          NaN           NaN
4                     -0.50  ...      NaN      NaN          NaN           NaN

   R/D (Min)  R/D Angle  DiscArea mm2  Cup Area mm2  Вік  Стать
0        NaN        NaN           NaN           NaN   35      1
1        NaN        NaN           NaN           NaN   35      1
2        NaN        NaN           NaN           NaN   23      2
3        NaN        NaN           NaN           NaN   23      2
4        NaN        NaN           NaN           NaN   41      2

[5 rows x 176 columns]
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Columns: 176 entries, Пацієнт to Стать
dtypes: float64(141), int64(34), object(1)
memory usage: 550.1+ KB
None

In [15]:
df = pd.read_csv("data/merged_data.csv")
df

,Пацієнт,Обстеження,Око,Гострота зору некорегована далека відстань,Корекція sph,Корекція cyl,Корекція cyl ax,Гострота зору максимально корегована далека відстань,Гострота зору некорегована далека відстань циклоплегія,Корекція циклоплегія sph,...,TSNIT I,TSNIT T,C/D Horizon,C/D Vertical,R/D (Min),R/D Angle,DiscArea mm2,Cup Area mm2,Вік,Стать
0,1,1,d,NaN,-4.00,0.00,0.0,1.0,0.05,-3.50,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,35,1
1,1,1,s,0.05,-3.75,-0.50,10.0,1.0,0.05,-3.50,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,35,1
2,2,1,d,0.04,-3.00,-1.00,100.0,0.8,0.04,-2.75,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,23,2
3,2,1,s,0.04,-3.00,-0.75,15.0,0.8,0.04,-2.75,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,23,2
4,3,1,d,0.20,-1.00,0.00,0.0,0.9,0.20,-0.50,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,41,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
395,198,1,s,0.03,-6.00,-0.75,170.0,1.0,0.03,-6.00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,25,2
396,199,1,d,0.03,-8.75,0.00,0.0,0.8,0.03,-8.25,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,30,2
397,199,1,s,0.03,-11.25,-0.50,40.0,0.8,0.03,-11.25,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,30,2
398,200,1,d,0.15,-1.75,-1.00,100.0,0.9,0.10,-1.75,...,153.0,78.0,0.31,0.20,0.29,177.0,2.31,0.14,35,2
399,200,1,s,0.10,-2.25,-1.25,55.0,1.0,0.10,-2.00,...,164.0,108.0,0.40,0.36,0.26,330.0,1.66,0.24,35,2

In [16]:
df = df.drop(columns=['Обстеження'])
df

,Пацієнт,Око,Гострота зору некорегована далека відстань,Корекція sph,Корекція cyl,Корекція cyl ax,Гострота зору максимально корегована далека відстань,Гострота зору некорегована далека відстань циклоплегія,Корекція циклоплегія sph,Корекція циклоплегія cyl,...,TSNIT I,TSNIT T,C/D Horizon,C/D Vertical,R/D (Min),R/D Angle,DiscArea mm2,Cup Area mm2,Вік,Стать
0,1,d,NaN,-4.00,0.00,0.0,1.0,0.05,-3.50,0.00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,35,1
1,1,s,0.05,-3.75,-0.50,10.0,1.0,0.05,-3.50,-0.50,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,35,1
2,2,d,0.04,-3.00,-1.00,100.0,0.8,0.04,-2.75,-1.25,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,23,2
3,2,s,0.04,-3.00,-0.75,15.0,0.8,0.04,-2.75,-1.00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,23,2
4,3,d,0.20,-1.00,0.00,0.0,0.9,0.20,-0.50,-0.50,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,41,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
395,198,s,0.03,-6.00,-0.75,170.0,1.0,0.03,-6.00,-0.75,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,25,2
396,199,d,0.03,-8.75,0.00,0.0,0.8,0.03,-8.25,-0.75,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,30,2
397,199,s,0.03,-11.25,-0.50,40.0,0.8,0.03,-11.25,-0.50,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,30,2
398,200,d,0.15,-1.75,-1.00,100.0,0.9,0.10,-1.75,-1.00,...,153.0,78.0,0.31,0.20,0.29,177.0,2.31,0.14,35,2
399,200,s,0.10,-2.25,-1.25,55.0,1.0,0.10,-2.00,-1.00,...,164.0,108.0,0.40,0.36,0.26,330.0,1.66,0.24,35,2

In [17]:
missing = df.isnull().sum()

missing_percent = (missing / len(df)) * 100
missing_percent = missing_percent[missing_percent > 0].sort_values(ascending=False)

missing_percent

C/D Horizon                                   74.75
Cup Area mm2                                  74.75
R/D (Min)                                     74.75
C/D Vertical                                  74.75
R/D Angle                                     74.25
                                              ...
Кератометрія циклоплегії R2 D                  0.50
Кератометрія циклоплегії deg                   0.50
Кератометрія циклоплегії AVE D                 0.50
Рефрактометрія циклоплегія Cylynder            0.50
Гострота зору некорегована далека відстань     0.25
Length: 79, dtype: float64

In [18]:
columns_to_drop = missing_percent[missing_percent > 30].index
df_cleaned = df.drop(columns=columns_to_drop)
df_cleaned

,Пацієнт,Око,Гострота зору некорегована далека відстань,Корекція sph,Корекція cyl,Корекція cyl ax,Гострота зору максимально корегована далека відстань,Гострота зору некорегована далека відстань циклоплегія,Корекція циклоплегія sph,Корекція циклоплегія cyl,...,вертикальний 6,Axial length (mm),Anterior chamber depth,Lens thickness,Flat meridian K1 (D),Step meridian K1 (ax),White to white (mm),Pupil diameter (mm),Вік,Стать
0,1,d,NaN,-4.00,0.00,0.0,1.0,0.05,-3.50,0.00,...,42.5,26.06,3.84,3.36,42.19,43.15,12.18,4.58,35,1
1,1,s,0.05,-3.75,-0.50,10.0,1.0,0.05,-3.50,-0.50,...,44.0,25.74,3.78,3.44,42.55,44.66,12.14,3.07,35,1
2,2,d,0.04,-3.00,-1.00,100.0,0.8,0.04,-2.75,-1.25,...,44.0,24.60,3.86,3.24,45.17,45.83,11.67,4.10,23,2
3,2,s,0.04,-3.00,-0.75,15.0,0.8,0.04,-2.75,-1.00,...,44.7,24.38,3.37,3.24,45.36,46.59,11.51,4.07,23,2
4,3,d,0.20,-1.00,0.00,0.0,0.9,0.20,-0.50,-0.50,...,43.1,24.11,3.26,4.33,43.24,44.41,12.02,3.69,41,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
395,198,s,0.03,-6.00,-0.75,170.0,1.0,0.03,-6.00,-0.75,...,44.9,26.55,4.37,3.26,43.40,44.61,12.68,5.31,25,2
396,199,d,0.03,-8.75,0.00,0.0,0.8,0.03,-8.25,-0.75,...,44.4,26.72,3.62,3.68,43.37,43.92,12.16,4.53,30,2
397,199,s,0.03,-11.25,-0.50,40.0,0.8,0.03,-11.25,-0.50,...,44.2,27.67,3.62,3.70,43.55,44.31,12.08,4.13,30,2
398,200,d,0.15,-1.75,-1.00,100.0,0.9,0.10,-1.75,-1.00,...,NaN,23.09,3.12,3.99,44.73,45.89,11.25,3.38,35,2
399,200,s,0.10,-2.25,-1.25,55.0,1.0,0.10,-2.00,-1.00,...,44.5,23.32,3.17,4.01,44.59,45.90,11.27,3.66,35,2

In [19]:
numeric_cols = df_cleaned.select_dtypes(include=['number']).columns
df_cleaned[numeric_cols] = df_cleaned[numeric_cols].fillna(df_cleaned[numeric_cols].median())
df_cleaned.isnull().sum()

Пацієнт                                       0
Око                                           0
Гострота зору некорегована далека відстань    0
Корекція sph                                  0
Корекція cyl                                  0
                                             ..
Step meridian K1 (ax)                         0
White to white (mm)                           0
Pupil diameter (mm)                           0
Вік                                           0
Стать                                         0
Length: 144, dtype: int64

In [20]:
# target_col = 'Гострота зору некорегована далека відстань'
#
# pivot_df = df_cleaned.pivot(index='Пацієнт', columns='Око', values=target_col)
# pivot_df.columns = ['OD', 'OS']
# corr_coef, p_value = pearsonr(pivot_df['OD'], pivot_df['OS'])
#
# plt.figure(figsize=(5, 5))
# sns.regplot(x='OD', y='OS', data=pivot_df,
#             scatter_kws={'alpha':0.5, 'color':'blue'},
#             line_kws={'color':'red', 'label': f'Лінія регресії'})
#
# plt.title(f'Pearson r = {corr_coef:.2f}, p_value = {p_value:.2f}', fontsize=14)
# plt.xlabel('Праве око', fontsize=12)
# plt.ylabel('Ліве око', fontsize=12)
# plt.legend()
# plt.grid(True, linestyle=':', alpha=0.6)
# plt.show()

In [21]:
# cols_to_mean = [col for col in numeric_cols if col not in ['Пацієнт', 'Вік', 'Стать']]
# agg_dict = {col: 'mean' for col in cols_to_mean}
# agg_dict['Вік'] = 'first'
# agg_dict['Стать'] = 'first'
#
# df_aggregated = df_cleaned.groupby('Пацієнт').agg(agg_dict).reset_index()

In [22]:
df_cleaned.drop(columns=['Око', 'Гострота зору максимально корегована далека відстань', 'Гострота зору некорегована далека відстань циклоплегія', 'Гострота зору максимально корегована далека відстань циклоплегія', 'Гострота зору некорегована близька відстань', 'Гострота зору максимально корегована близька відстань'], inplace=True)

df_cleaned['Стать'] = df_cleaned['Стать'].map({1: 0, 2: 1})
df_cleaned.to_csv("data/prepared_data.csv", index=False)